-- TODO: here, I want to create a central directory for ui elements
-- I want to start with making all plugins access their symbols from here
--
-- Here I surely can take some inspiration from the LazyVim config
